name: snap-wx-simple
summary: A simple wxpython program
description: |
      rubber band async wxpython - drag a rubber band around the screen

version: git
grade: stable
confinement: devmode
base: core20
architectures:
  # - build-on: [arm64, armhf, amd64]
  - build-on: [amd64]

apps:
  snap-wx-simple:
    command: bin/rubber
    plugs: [home, network, network-bind, removable-media, pulseaudio]
  python-v:
      command: bin/python3 -V

environment:
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/snap-wx-simple/current/usr/lib/x86_64-linux-gnu/pulseaudio

parts:
  build-the-python-stuff-please:
    plugin: python
    source: .
    python-packages:
        - wheel # genx does this
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.2.0-cp38-cp38-linux_x86_64.whl
        - wxasync
    stage-packages:
      - libcairo2
      - libfontconfig1
      - cruft-common
      - libgl1
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0 #
      - libgstreamer1.0-dev
      - libgtk-3-0
      - libjavascriptcoregtk-4.0-18
      - libjpeg-turbo8
      - libnotify4
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-32-0
      - libpng16-16
      - libsdl2-2.0-0 #
      - libsm6 #
      - libtiff5
      - libwayland-client0
      - libwayland-egl1
      - libwebkit2gtk-4.0-37 # 
      - libx11-6
      - libxtst6 #
      - libxxf86vm1
      - nsight-systems
      - nxagent
      - primus-libs
      - libpulse0
      - libpulse-dev
      - pulseaudio
      # try these done by genx, lets try them
      - libegl1
      - libpsm2-2-compat
      - libgomp1-amd64-cross
      - libtbb2
    # this after step done by genx, maybe it will help with the font problem
    after: [desktop-gnome-platform]

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  my-font-part:
    # this part doesn't help fix the square rectangle problem
    plugin: nil
    stage-packages:
      - fonts-noto-color-emoji
      - fonts-dejavu
      - fontconfig
      - fontconfig-config
      - fonts-liberation
      - ttf-ubuntu-font-family
      - ttf-mscorefonts-installer
  
# this done by genx, maybe it will help with the font problem
plugs:
  gnome-3-38-2004:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-38-2004
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
