name: snap-wx-simple
summary: A simple wxpython program
description: |
      rubber band async wxpython - drag a rubber band around the screen

version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

# Invoke the command with snap-py-simple
# Invoke the python version with snap-py-simple.python-v
apps:
  snap-wx-simple:
    command: bin/rubber
    plugs: [home, network, network-bind, removable-media]
  python-v:
      command: bin/python3 -V

parts:
  build-the-python-stuff-please:
    plugin: python
    source: .
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.2.0-cp38-cp38-linux_x86_64.whl
        - wxasync
    # The 'build-the-python-stuff-please' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entry for this part
    # This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
    stage-packages:
      - libcairo2
      - libfontconfig1
      - cruft-common
      - libgl1
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libgtk-3-0
      - libjavascriptcoregtk-4.0-18
      - libjpeg-turbo8
      - libnotify4
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-32-0
      - libpng16-16
      - libsdl2-2.0-0
      - libsm6
      - libtiff5
      - libwayland-client0
      - libwayland-egl1
      - libwebkit2gtk-4.0-37
      - libx11-6
      - libxtst6
      - libxxf86vm1
      - nsight-systems
      - nxagent
      - primus-libs



    # name: rubberband
    # version: git
    # summary: 'rubberband test'
    # description: |
    #   rubber ha ha
    #   and just testing this

    # grade: stable # devel # must be 'stable' to release into candidate/stable channels
    # confinement: strict # use 'strict' once you have the right plugs and slots
    # base: core22
    # apps:
    #     rubber:
    #         command: python3 $SNAP/rubber_band_async.py
    #         extensions: [gnome]
    #         plugs: [unity7, audio-playback, home, network]
    # parts:
    #   copy-stuff:
    #     plugin: dump
    #     source: ./src
    #   rubber:
    #     plugin: python
    #     source: ./src
    #     python-packages:
    #         - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
    #         - wxasync
    #     python-requirements:
    #         - /root/project/requirements.txt

