name: snap-wx-simple
summary: A simple wxpython program
description: |
      rubber band async wxpython - drag a rubber band around the screen

version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

# Invoke the command with snap-py-simple
# Invoke the python version with snap-py-simple.python-v
apps:
  snap-wx-simple:
    command: bin/rubber
    plugs: [home, network, network-bind, removable-media]
  python-v:
      command: bin/python3 -V

parts:
  build-the-python-stuff-please:
    plugin: python
    source: .
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.2.0-cp38-cp38-linux_x86_64.whl
        - wxasync
    # The 'build-the-python-stuff-please' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entry for this part
    # This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
    stage-packages:
      - libpng16-16
      - libEGL.so.1
      - libGL.so.1
      - libSDL2-2.0.so.0
      - libSM.so.6
      - libX11.so.6
      # - libXtst.so.6
      - libxtst6
      - libXxf86vm.so.1
      # - libcairo.so.2
      - libcairo2
      - libfontconfig.so.1
      - libgdk-3.so.0
      - libgdk_pixbuf-2.0.so.0
      - libgstreamer-1.0.so.0
      - libgstvideo-1.0.so.0
      - libgtk-3.so.0
      - libjavascriptcoregtk-4.0.so.18
      # - libjpeg.so.8
      - libjpeg-turbo8
      - libnotify.so.4
      - libpango-1.0.so.0
      # - libpangocairo-1.0.so.0
      - libpangocairo-1.0-0
      - libpangoft2-1.0.so.0
      - libpcre2-32.so.0
      - libtiff.so.5
      - libwayland-client.so.0
      - libwayland-egl.so.1
      - libwebkit2gtk-4.0.so.37

        



    # name: rubberband
    # version: git
    # summary: 'rubberband test'
    # description: |
    #   rubber ha ha
    #   and just testing this

    # grade: stable # devel # must be 'stable' to release into candidate/stable channels
    # confinement: strict # use 'strict' once you have the right plugs and slots
    # base: core22
    # apps:
    #     rubber:
    #         command: python3 $SNAP/rubber_band_async.py
    #         extensions: [gnome]
    #         plugs: [unity7, audio-playback, home, network]
    # parts:
    #   copy-stuff:
    #     plugin: dump
    #     source: ./src
    #   rubber:
    #     plugin: python
    #     source: ./src
    #     python-packages:
    #         - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
    #         - wxasync
    #     python-requirements:
    #         - /root/project/requirements.txt

